### ISSUE TITLE
Unexpected behaviour with empty list of args

### ISSUE THREAD

**Issue by nbirillo** [JetBrains-Research/paddle#65]
It would be great to inform the user about an empty list of arguments instead of the current error message:

```
tasks:
  run:
    - id: prepare_course_data
      entrypoint: jba/processing/prepare_course_data.py
      args:
``` 
The current error: `class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')`
